linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - gofmt
    - goimports
    - typecheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0